spring:
  application:
    name: fleche-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

server:
  port: 8080

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://fleche-eureka-user:uelsem-ahh--orndcaa@localhost:8761/eureka/
