spring:
  application:
    name: like-api

  datasource:
    url: jdbc:postgresql://localhost:5432/fleche
    username: postgres
    password: 15421542

  kafka:
    bootstrap-servers: 'http://localhost:29092'
    consumer:
      group-id: fleche-like-group
      auto-offset-reset: earliest

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc.lob.non_contextual_creation: true
        show_sql: false

fleche:
  config:
    kafka:
      server-url: 'http://localhost:29092'
      topics:
        fleche-like: 'fleche.like'

server:
  port: 8081