spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/fleche
    username: postgres
    password: 15421542

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc.lob.non_contextual_creation: true
        show_sql: false

  kafka:
    bootstrap-servers: 'http://localhost:29092'
    consumer:
      group-id: fleche-like-group
      auto-offset-reset: earliest

fleche:
  config:
    kafka:
      server-url: 'http://localhost:29092'
      topics:
        fleche-like: 'fleche.like'

server:
  port: 8085

auth:
  key:
    secret: "uPzby0R7fAVoP43sGjKd4Z5QzLmFZyvBzk9z8rGxgRs="

springdoc:
  openapi:
    title: 'Fleche API'
    description: 'O novo sucesso da galera'
    version: '1.0.0'